# Generated by Django 4.0 on 2021-12-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=123, max_length=20, null='True')),
                ('branch', models.CharField(max_length=20, null='True')),
                ('address', models.TextField()),
                ('fathername', models.CharField(max_length=15, null='True')),
                ('mothername', models.CharField(max_length=15, null='True')),
            ],
        ),
    ]
