# Generated by Django 4.0 on 2021-12-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='college',
            new_name='disp',
        ),
    ]
