# Generated by Django 4.0 on 2021-12-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='func1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('age', models.IntegerField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('phonenumber', models.IntegerField(max_length=15)),
            ],
        ),
    ]
